### PR TITLE
coffee-file: Changed yocto image from balena-image to balena-image-flasher

### PR DESCRIPTION
**Pull request by joris-bright**
Changelog-entry: Changed yocto image from balena-image to balena-image-flasher
Signed-off-by: joris-bright <joris@bright-energy.eu>

### CODE REVIEW

**Comment by floion** [comment]
Hi, can you rebase this PR please?

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
Superseded by https://github.com/balena-os/balena-kontron-mx8mm/pull/53 which also updates the deploy artifact name

**Pull request closed without merging**
